"""initial migration

Revision ID: 24319a944774
Revises: 
Create Date: 2022-01-18 08:22:46.411802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24319a944774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_table('coordinators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('middlename', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_coordinators_created_at'), 'coordinators', ['created_at'], unique=False)
    op.create_table('nextofkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('middlename', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_nextofkins_created_at'), 'nextofkins', ['created_at'], unique=False)
    op.create_table('passwordresets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_passwordresets_created_at'), 'passwordresets', ['created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('old_password_hash', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('middlename', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system_user', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('nins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nin', sa.String(length=16), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('middlename', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', 'na', name='gender_enum_1'), nullable=False),
    sa.Column('birthdate', sa.String(length=16), nullable=False),
    sa.Column('image', sa.String(length=160), nullable=False),
    sa.Column('pulled_by', sa.String(length=50), nullable=False),
    sa.Column('nin_type', sa.Enum('national', 'autogenerated', name='loan_nin_type_types'), server_default='national', nullable=False),
    sa.ForeignKeyConstraint(['pulled_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_nins_created_at'), 'nins', ['created_at'], unique=False)
    op.create_table('permission_role',
    sa.Column('permission_id', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.uuid'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.uuid'], )
    )
    op.create_table('role_group',
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.uuid'], )
    )
    op.create_table('user_group',
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], )
    )
    op.create_table('useraccounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=False),
    sa.Column('nin', sa.String(length=16), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', 'na', name='gender_type_2'), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('next_of_kin_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_uuid', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['next_of_kin_uuid'], ['nextofkins.uuid'], ),
    sa.ForeignKeyConstraint(['nin'], ['nins.nin'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_useraccounts_created_at'), 'useraccounts', ['created_at'], unique=False)
    
   
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useraccounts_created_at'), table_name='useraccounts')
    op.drop_table('useraccounts')
    op.drop_table('user_group')
    op.drop_table('role_group')
    op.drop_table('permission_role')
    op.drop_index(op.f('ix_nins_created_at'), table_name='nins')
    op.drop_table('nins')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_passwordresets_created_at'), table_name='passwordresets')
    op.drop_table('passwordresets')
    op.drop_index(op.f('ix_nextofkins_created_at'), table_name='nextofkins')
    op.drop_table('nextofkins')
    op.drop_index(op.f('ix_coordinators_created_at'), table_name='coordinators')
    op.drop_table('coordinators')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
