"""loan beneficiary added

Revision ID: 6d7fe1cd8792
Revises: f0e81ab553f9
Create Date: 2022-01-28 22:09:13.612275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7fe1cd8792'
down_revision = 'f0e81ab553f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_account_uuid', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('marital_status',  sa.Enum("married", "single" , name ="marital_status"), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('language_spoken', sa.Enum("housa","yoruba",'igbo',"english", name ="language_spoken",), nullable=False),
    sa.Column('riwaya', sa.Enum("hafs", "warsh", "qalun", "al_duri", "khallad", " Khalaf ", "shuab", "ibn_amir", "hisham", "thakwan",  "albuzze", "qumbul", "as_sosee", name="riwaya_type"), nullable=False),
    sa.Column('category', sa.Enum("sixty_hizbs_tafsir", "sixty_Hizbs", "fourty_Hizbs", "twenty_Hizbs", "ten_hizbs_and_tangeem", "two_Hizbs",  name="category_type"), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['user_account_uuid'], ['useraccounts.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_students_created_at'), 'students', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_created_at'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
