"""added vehicle color

Revision ID: f0e81ab553f9
Revises: 24319a944774
Create Date: 2022-01-26 09:00:29.891512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e81ab553f9'
down_revision = '24319a944774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
