#!/usr/bin/env python
# -=-<[ Bismillahirrahmanirrahim ]>-=-
# -*- coding: utf-8 -*-
# @Date    : 2021-05-10 06:11:10
# @Author  : Dahir Muhammad Dahir
# @Description : something cool


from sqlalchemy import Column, String, Integer, Enum, ForeignKey
from sqlalchemy.orm import relationship
from app.config.database import Base
from app.mixins.columns import BaseMixin


# =========[ NIN Models ]=========

class NIN(BaseMixin, Base):
    nin = Column(String(length=16), unique=True, nullable=False)
    firstname = Column(String(length=45), nullable=False)
    middlename = Column(String(length=45), default="", nullable=False)
    lastname = Column(String(length=45), nullable=False)
    address = Column(String(length=160), nullable=False)
    phone = Column(String(length=16), nullable=False)
    gender = Column(Enum("m", "f", "na", name="gender_enum_1"), nullable=False)
    birthdate = Column(String(length=16), nullable=False)
    image = Column(String(length=160), nullable=False)
    pulled_by = Column(String(length=50), ForeignKey("users.uuid"), nullable=False)
    nin_type = Column(Enum("national", "autogenerated", name="loan_nin_type_types"), \
        nullable=False, server_default="national")

